# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e53afba48d0f12669f94d62609978761760ccf674ce1c4572bc5efe92d49f7e540939864714c1e89d4789c668959198e9364e3e6146f38fbbfdddd7b1974496

test:
  secret_key_base: a77043aa45a938d04b707e5112c321eaf2621ece95415ceb54e402d8324f3d9a475b4e5255143d71448f3c76b9b2cb826845753667af6efc7b9d16bcde16fd58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
